#!/usr/bin/env bash

set -euo pipefail

python3 <<END
from i3ipc import Connection

i3 = Connection()


def mapper(v):
    return v.focused == True


windows = i3.get_tree().find_focused().workspace().leaves()
window = list(filter(mapper, windows))[0]
length = len(windows)
accent_color = "@g9@" if length > 1 else "@fg1@"
maybe_sep = " " if length > 1 else ""

window_title = "<span color=\"#@fg1@\" style=\"italic\" font_size=\"small\" background=\"#@bg1@\">{}{}</span>".format(
    window.window_title, maybe_sep)
workspace_stats = "<span color=\"#{}\" background=\"#@bg1@\" style=\"italic\" font_size=\"small\">[{}]</span>".format(
    accent_color, length)

workspace_stats = workspace_stats if length > 1 else ""

print("{}{}".format(window_title, workspace_stats))
END
